# Generated by Django 3.2.9 on 2021-11-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refreshed', models.CharField(max_length=50, unique=True)),
                ('open', models.CharField(max_length=50)),
                ('high', models.CharField(max_length=50)),
                ('low', models.CharField(max_length=50)),
                ('close', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
