# Generated by Django 3.2.9 on 2021-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_cryptoprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('last_refreshed', models.CharField(max_length=50, unique=True)),
                ('exchange_rate', models.FloatField()),
                ('bid_price', models.FloatField()),
                ('ask_price', models.FloatField()),
            ],
        ),
    ]
